Update submodule imports

diff --git a/external_imported/sentry-native/external/crashpad/third_party/lss/lss/tests/Makefile b/external_imported/sentry-native/external/crashpad/third_party/lss/lss/tests/Makefile
--- a/external_imported/sentry-native/external/crashpad/third_party/lss/lss/tests/Makefile
+++ b/external_imported/sentry-native/external/crashpad/third_party/lss/lss/tests/Makefile
@@ -41,7 +41,11 @@ LDFLAGS += -static
 
 TESTS = \
 	fallocate \
+	getrandom \
+	lstat \
+	sigaction \
 	sigtimedwait \
+	stat \
 	unlink \
 
 all: check
@@ -55,7 +59,12 @@ all: check
 %_run: %_test
 	@t=$(@:_run=_test); \
 	echo "./$$t"; \
-	if ! env -i ./$$t; then \
+	env -i ./$$t; \
+	exit_status=$$?; \
+	if [ $$exit_status = 77 ]; then \
+		echo "SKIP: $$t"; \
+	elif [ $$exit_status != 0 ]; then \
+		echo "FAIL: $$t"; \
 		env -i strace -f -v ./$$t; \
 		echo "TRY: gdb -q -ex r -ex bt ./$$t"; \
 		exit 1; \
