debian fix

diff --git a/.github/workflows/deploy_debian_repo.yml b/.github/workflows/deploy_debian_repo.yml
--- a/.github/workflows/deploy_debian_repo.yml
+++ b/.github/workflows/deploy_debian_repo.yml
@@ -257,6 +257,52 @@ jobs:
 
           debian_mirror="http://deb.debian.org/debian"
 
+          register_qemu_binfmt() {
+            local arch="$1"
+            local qemu_target=""
+
+            case "${arch}" in
+              arm64)
+                qemu_target="aarch64"
+                ;;
+              armel|armhf)
+                qemu_target="arm"
+                ;;
+              *)
+                return 0
+                ;;
+            esac
+
+            if [[ "$(dpkg --print-architecture)" == "${arch}" ]]; then
+              return 0
+            fi
+
+            if [[ ! -x "/usr/bin/qemu-${qemu_target}-static" ]]; then
+              echo "Missing qemu-${qemu_target}-static for ${arch}" >&2
+              exit 1
+            fi
+
+            mountpoint -q /proc/sys/fs/binfmt_misc ||
+              mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
+
+            if [[ -e "/proc/sys/fs/binfmt_misc/qemu-${qemu_target}" ]]; then
+              return 0
+            fi
+
+            curl --fail --silent --show-error --location \
+              https://raw.githubusercontent.com/qemu/qemu/master/scripts/qemu-binfmt-conf.sh \
+              --output /tmp/qemu-binfmt-conf.sh
+            chmod +x /tmp/qemu-binfmt-conf.sh
+
+            if ! /tmp/qemu-binfmt-conf.sh --path /usr/bin --suffix -static --persistent "${qemu_target}"; then
+              /tmp/qemu-binfmt-conf.sh \
+                --qemu-path /usr/bin \
+                --qemu-suffix -static \
+                --persistent yes \
+                "${qemu_target}"
+            fi
+          }
+
           for distro in "${debian_suites[@]}"; do
             rm -rf EternalTerminal
             mkdir EternalTerminal
@@ -278,6 +324,8 @@ jobs:
             popd
 
             for arch in "${debian_arches[@]}"; do
+              register_qemu_binfmt "${arch}"
+
               chroot_tarball="${HOME}/.cache/sbuild/${distro}-${arch}-sbuild.tar"
               chroot_dir="${HOME}/sbuild-chroots/${distro}-${arch}"
               result_dir="${PWD}/sbuild-results/${distro}-${arch}"
